# Generated by Django 2.2.5 on 2019-10-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('v_author', 'Can view the author'), ('can_publish_author', 'Can publish an author'))},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('v_book', 'Can view the book'), ('can_publish_book', 'Can publish a book'))},
        ),
    ]
