# Generated by Django 2.2.5 on 2019-09-29 08:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190925_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='book', on_delete=django.db.models.deletion.CASCADE, to='catalog.BookLanguage'),
        ),
    ]
