# Generated by Django 2.2.5 on 2019-09-29 08:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190929_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='book', chained_model_field='book', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='catalog.BookLanguage'),
        ),
    ]
