# Generated by Django 2.2.5 on 2019-09-29 09:55

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190929_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='book', chained_model_field='book', on_delete=django.db.models.deletion.CASCADE, to='catalog.BookLanguage'),
        ),
    ]
