# Generated by Django 2.2.5 on 2019-09-29 10:24

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190929_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='book',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='language', chained_model_field='languages', horizontal=True, to='catalog.Book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Language'),
        ),
    ]
