# Generated by Django 2.2.5 on 2019-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191006_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('b', 'Reserved'), ('m', 'Maintenance'), ('ol', 'On Loan')], default='Available', max_length=32),
        ),
    ]
