# Generated by Django 2.2.5 on 2019-10-13 10:07

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20191008_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('v_author', 'Can view the author'), ('can_publish_author', 'Can publish an author'))},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('v_book', 'Can view the book'), ('can_publish_book', 'Can publish a book'))},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back_date',
            field=models.DateField(null=True, validators=[catalog.models.BookInstance.validate_date]),
        ),
    ]
