# Generated by Django 2.2.5 on 2019-10-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191013_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('view_all_instances', 'Can view all instances'),)},
        ),
    ]
